name: tod_list_managmant
description: Todo for company and people.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
  # sdk: '>=3.0.1 <4.0.0'


## CI / CD 
scripts:
  generate:
    all: ./scripts/generate-all.sh
    translations: ./scripts/generate-translations.sh
  build_runner: flutter pub run build_runner build --delete-conflicting-outputs
  launch:
    dev: flutter run --flavor dev --dart-define=flavor=dev
    dev-preview: flutter run --flavor dev --dart-define=flavor=dev --dart-define=enableDevicePreview="true"
    qa: flutter run --flavor qa --dart-define=flavor=qa
    prod: flutter run --flavor prod --dart-define=flavor=prod
  test:
    all: flutter test
    exclude-goldens: flutter test --exclude-tags=golden
    goldens: flutter test --tags=golden test/presentation/goldens
    update-goldens: flutter test --tags=golden test/presentation/goldens --update-goldens
  analyze: flutter analyze --fatal-infos --fatal-warnings
  format: dart format --set-exit-if-changed lib
  fix: dart fix --apply
  build:
    apk:
      dev: flutter build apk --flavor=dev --dart-define=flavor=dev --debug
      qa: flutter build apk --flavor=qa --dart-define=flavor=qa --debug
      prod: flutter build apk --flavor=prod --dart-define=flavor=prod --debug
    release-apk:
      qa: flutter build apk --flavor=qa --dart-define=flavor=qa --release --obfuscate --split-debug-info=debug-info
      prod: flutter build apk --flavor=prod --dart-define=flavor=prod --release --obfuscate --split-debug-info=debug-info
    appbundle:
      dev: flutter build appbundle --flavor=dev --dart-define=flavor=dev
      qa: flutter build appbundle --flavor=qa --dart-define=flavor=qa
      prod: flutter build appbundle --flavor=prod --dart-define=flavor=prod
    ios:
      dev: flutter build ios --flavor=dev --dart-define=flavor=dev --debug --no-codesign
      qa: flutter build ios --flavor=qa --dart-define=flavor=qa --debug --no-codesign
      prod: flutter build ios --flavor=prod --dart-define=flavor=prod --debug --no-codesign
    web:
      dev: flutter build web --dart-define=flavor=dev
      qa: flutter build web --dart-define=flavor=qa
      prod: flutter build web --dart-define=flavor=prod

dependencies:
  flutter:
    sdk: flutter

  stacked_services: ^1.0.0 # - All ,no WEB

  # state management
  stacked: ^3.2.0
  stacked_hooks: ^0.2.3
  cupertino_icons: ^1.0.2
  # navigation
  auto_route: ^6.0.5
  # auto_route: ^5.0.4
  # inversion of control
  get_it: ^7.2.0
  get: ^4.6.5
  injectable: ^2.1.0
  flutter_hooks: ^0.18.6
  dio: ^5.0.3
  # http: ^0.13.5

  #### Write elegant reactive cross-platform client side application using observable states and event emitters.
  observable_ish: ^4.0.8
  image_picker: ^0.8.7  # - ANDROID / IOS / WEB 
  

  ## Notification
  ### Huawei - Only Android 
  huawei_push: ^6.7.0+300 # - ANDROID 
  ### RuStore - Only Android
  flutter_rustore_push: ^0.0.4 # - ANDROID 
  ### Firebase - Android / IOS
  firebase_core: ^2.12.0 # - ANDROID / IOS / MACOS / WINDOWS / WEB 
  firebase_messaging: ^14.6.0 # - ANDROID / IOS / MACOS / WEB 
  ## Authorization
  firebase_auth: ^4.6.0 # - ANDROID / IOS / MACOS / WEB 
  ### Firebase
  ### Huawei
  agconnect_auth: ^1.6.0+300 # - Android / IOS

  ## Deeplink / Dynamic link
  ### Firebase
  firebase_dynamic_links: ^5.3.0 # - Android / IOS
  ### Huawei
  agconnect_applinking: ^1.6.0+300 # - Android / IOS


  ## Redirect
  ### Store app (Google play / App story)
  # store_redirect: ^2.0.0  # - Android / IOS
  ### Для открытия play store, чтобы обновить приложение
  # launch_review: ^3.0.1  # - Android / IOS
  ### Phone app
  # telephony: ^0.2.0

  ## Share 
  share_plus: ^7.0.0   # - ANDROID / IOS / MACOS / WINDOWS / LINUX / WEB 

  ### пдгрузка списка
  # loadmore: ^2.0.1
  ### Scan QR Code
  # qr_code_scanner: ^1.0.0
  ### preview photo
  # photo_view: ^0.14.0
  ### Http request version and dev and release
  # package_info_plus: ^3.0.2
  ### Image chooise(change) and crop
  # photo_manager: ^2.0.7
  # extended_image: ^7.0.2
  # image_editor: ^1.3.0
  ### Either (монада) принимает два значения ошибка и результат
  # dartz: ^0.10.0
  ### Restart Native App
  # flutter_app_restart: ^1.0.0  # - ANDROID / IOS 

  ### Native permission
  permission_handler: ^10.0.0 # - ANDROID / IOS / WINDOWS
  ### Send Email 
  # flutter_email_sender: ^5.0.2  # - ANDROID / IOS 

  ## Crash Analitycs
  sentry_flutter: ^7.5.2  # - ANDROID / IOS / MACOS / WINDOWS / LINUX / WEB 
  # sentry_dio: ^7.5.0

  ## Localization / Internationalization
  easy_localization: ^3.0.1
  # flutter_localizations:
  #   sdk: flutter
  # intl: ^0.18.1

  # intl_phone_number_input: ^0.7.3+1
  # intl_phone_field: ^3.1.0
  
  ## OTHER
  animations: ^2.0.7
  email_validator: ^2.1.17
  cached_network_image: ^3.2.3   # - ANDROID / IOS / MACOS 

  flutter_modular: ^5.0.3

  google_fonts: ^4.0.3
  equatable: ^2.0.5
  # latlong2: ^0.8.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  path_provider: ^2.0.15
  ### NoSQL
  hive: ^2.2.3  # - ANDROID / IOS / MACOS / WINDOWS / LINUX / WEB 
  ### Wraps platform-specific persistent storage for simple data
  # encrypted_shared_preferences: ^3.0.1  # - ANDROID / IOS / MACOS / WINDOWS / LINUX / WEB 
  ### ORM SQL database
  drift: ^2.5.0   # - ANDROID / IOS / MACOS / WINDOWS / LINUX / WEB 
  ### SQL
  sqlite3_flutter_libs: ^0.5.13   # - ANDROID / IOS / MACOS / WINDOWS / LINUX 
  collection: ^1.17.0  # - ANDROID / IOS / MACOS / WINDOWS / LINUX / WEB 
  path: ^1.8.2 # - ANDROID / IOS / MACOS / WINDOWS / LINUX / WEB 
  shimmer: ^2.0.0
  tuple: ^2.0.1  # - ANDROID / IOS / MACOS / WINDOWS / LINUX / WEB 
  # faker: ^2.1.0

  # flutter_displaymode: ^0.5.0  # - ANDROID 

  connectivity_plus: ^3.0.6  # - ANDROID / IOS / MACOS / WINDOWS / LINUX / WEB 
  
  ## Animation   
  rive: ^0.10.4   # - ANDROID / IOS / MACOS / WINDOWS / WEB 
  lottie: ^2.3.2  # - ANDROID / IOS / MACOS / WINDOWS / LINUX / WEB 
  flutter_animate: 4.1.1+1
  page_transition: 2.0.4
  # flutter_staggered_animations: ^1.0.0
  
  ### NEW OTHER 
  # auto_size_text: 3.0.0
  # flutter_cache_manager: 3.3.0
  # font_awesome_flutter: 10.1.0
  # from_css_color: 2.0.0
  # json_path: 0.4.1
  # sqflite: 2.2.6
  # timeago: 3.2.2
  # url_launcher: 6.1.10

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  #### TEST
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  
  ### Diagram UML for code нужен только при авто генерации UML из кода
  # dcdg: ^4.0.0

  # mock_web_server: ^4.1.1
  # build_runner: ^2.4.6
  build_runner: ^2.3.3
  # auto_route_generator:
  auto_route_generator: ^6.0.3
  injectable_generator: ^2.1.5
  # mockito: ^5.4.0
  drift_dev: ^2.5.2
  freezed: ^2.3.2
  # golden_toolkit: ^0.15.0
  # meta: ^1.8.0
  mocktail: ^0.3.0
  # mason: ^0.1.0-dev.47

  ##
  # bdd_widget_test: ^1.6.0
  # test: ^1.24.3
  faker: ^2.1.0
  ### Dio
  # http_mock_adapter: ^0.4.4
  # dio_mock_interceptor: ^1.0.0+1
  # state_notifier_test: ^0.0.9
  # test_cov_console: ^0.2.2





flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
