version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8096:5332'
    environment:
      # POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      POSTGRES_USER: postgres
      POSTGRES_DB: server_serverpod
      # POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_PASSWORD: "vQqBMZGpMR8ooIEq4qb8E8aH57qUpei1"
      ## first-default data "vQqBMZGpMR8ooIEq4qb8E8aH57qUpei1"
      ## sha-256 "21163f9c487dbefeff421cd03a63bdd320a3ad639b25f3cb4f732050a8823197" 
      ## md5 = "a500b93bd1d753f1155876ea03d3b6de"
    volumes:
      - server_serverpod_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "ZeMBX5QokH6keI6MjOJhPB9gnaIErolZ"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  server_serverpod_data:
